name: Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, GitHub Actions"
      - run: ls -la
